[platformio]
default_envs = supermini

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:supermini]
board = esp32-c3-devkitm-1
board_build.flash_mode = dio

build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
build_src_filter = +<*> -<main.cpp> -<main-esp-now-lilyGo.cpp> -<main-esp-now-gateway.cpp> 

[env:lilygo]

board = esp32dev 
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9
build_src_filter = +<*> -<main.cpp> -<main-esp-now-supermini.cpp> -<main-esp-now-gateway.cpp> 

[env:gateway]
board = esp32dev 
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9
    knolleary/PubSubClient @ ^2.8
    knolleary/PubSubClient @ ^2.8
build_src_filter = +<*> -<main.cpp> -<main-esp-now-supermini.cpp>  -<main-esp-now-lilyGo.cpp>

